package sk.eea.arttag.game.model;

public enum GameEvent {

	GAME_CREATED,
//	STARTED,
	ROUND_STARTED,
	TAGS_SELECTED,
	PLAYER_OWN_CARD_SELECTED,
//	ALL_PLAYERS_OWN_CARD_SELECTED,
	PLAYER_TABLE_CARD_SELECTED,
//	ALL_PLAYERS_TABLE_CARD_SELECTED,
//	ROUND_FINISHED,
	PLAYER_READY_FOR_NEXT_ROUND,
	TIMEOUT,
	PLAYER_JOINED,
	PLAYER_DISCONNECTED
}
