package sk.eea.arttag.game.model;

public enum GameStatus {

	NEW, 
	CREATED,
	ROUND_STARTED,
	ROUND_TAGS_SELECTED,
	ROUND_OWN_CARDS_SELECTED,
	ROUND_TABLE_CARDS_SELECTED,
	ROUND_FINISHED,
	FINISHED
}
